### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'iid'

### ISSUE THREAD

**Issue by ZhangXiaohan-TJU** [SCXsunchenxi/TEST#1]
I have encountered the following error, how should I solve it？
Traceback (most recent call last):
  File "main_encoder.py", line 183, in <module>
    main_classification(config)
  File "main_encoder.py", line 68, in main_classification
    encoder_classifier = fit_encoder_classifier_parameters(text_prototype=prototype_embeddings, dataset_x=encoder_train_data, dataset_labels=encoder_train_labels, cuda=encoder_cuda, gpu=encoder_gpu, local_rank=-1,
  File "/share/home/tj04211/TEST-main/running.py", line 521, in fit_encoder_classifier_parameters
    return classifier.fit(
  File "/share/home/tj04211/TEST-main/encoders/wrapper.py", line 801, in fit
    self.classifier = self.fit_classifier(features, y)
  File "/share/home/tj04211/TEST-main/encoders/wrapper.py", line 641, in fit_classifier
    grid_search = sklearn.model_selection.GridSearchCV(
TypeError: __init__() got an unexpected keyword argument 'iid'

**Comment by skafai** [comment]
The problem here is that that authors are using an old version of sklearn. In the new versions, this parameter is already removed. You can fix it by either using an older version or remove this parameter.
